services:
  parakeet-docker:
    build: .
    image: ghcr.io/gargomoma/parakeet-docker:latest
    container_name: parakeet-docker
    restart: unless-stopped
    ports:
      - "10300:10300"
      - "10301:10301"
    user: "1000:1000"
    volumes:
      - models:/models

volumes:
  models:
